#if UNITY_EDITOR
using UnityEditor;
using UnityEngine;
using UnityEngine.UI;
using TMPro;
namespace Everlight.Tales.UI.Editor
{
 public static class WorkbenchMaterialsLayoutMigration
 {
  const string Path="Assets/Game/Prefabs/UI/WorkbenchPage.prefab";
  [MenuItem("Game Framework/EverlightTales/UI/修复材料页滚动列表与详情")]
  public static void Apply(){if(EditorApplication.isPlaying)throw new System.InvalidOperationException("请先停止 Play Mode。"); GameObject root=PrefabUtility.LoadPrefabContents(Path); try{Transform p=root.transform.Find("Panel_Home/Panel_HomeArea/Panel_Workbench/Panel_WorkbenchBody/Panel_Materials")??root.transform.Find("Panel_Workbench/Panel_WorkbenchBody/Panel_Materials"); if(p==null)throw new System.InvalidOperationException("缺少 Panel_Materials"); Object.DestroyImmediate(p.GetComponent<VerticalLayoutGroup>());Object.DestroyImmediate(p.GetComponent<ContentSizeFitter>()); RectTransform scroll=R(p,"MaterialsScroll"); scroll.anchorMin=new Vector2(0,1);scroll.anchorMax=Vector2.one;scroll.pivot=new Vector2(.5f,1);scroll.offsetMin=new Vector2(12,410);scroll.offsetMax=new Vector2(-12,-18);Ensure<Image>(scroll.gameObject).color=new Color(0,0,0,0);ScrollRect sr=Ensure<ScrollRect>(scroll.gameObject);sr.horizontal=false;sr.vertical=true;sr.movementType=ScrollRect.MovementType.Clamped;RectTransform vp=R(scroll,"Viewport");Stretch(vp);Ensure<Image>(vp.gameObject).color=new Color(0,0,0,0);Ensure<RectMask2D>(vp.gameObject);RectTransform c=R(vp,"MaterialsContent");c.anchorMin=new Vector2(0,1);c.anchorMax=new Vector2(1,1);c.pivot=new Vector2(.5f,1);c.anchoredPosition=Vector2.zero;c.sizeDelta=Vector2.zero;VerticalLayoutGroup l=Ensure<VerticalLayoutGroup>(c.gameObject);l.padding=new RectOffset(0,12,0,12);l.spacing=8;l.childControlWidth=true;l.childControlHeight=false;l.childForceExpandWidth=true;l.childForceExpandHeight=false;ContentSizeFitter f=Ensure<ContentSizeFitter>(c.gameObject);f.horizontalFit=ContentSizeFitter.FitMode.Unconstrained;f.verticalFit=ContentSizeFitter.FitMode.PreferredSize;sr.viewport=vp;sr.content=c;RectTransform d=R(p,"Panel_MaterialDetail");d.anchorMin=Vector2.zero;d.anchorMax=new Vector2(1,0);d.pivot=new Vector2(.5f,0);d.anchoredPosition=new Vector2(0,18);d.sizeDelta=new Vector2(-24,370);Ensure<Image>(d.gameObject).color=new Color(.06f,.08f,.1f,.94f);RectTransform icon=R(d,"Icon");icon.anchorMin=new Vector2(0,1);icon.anchorMax=new Vector2(0,1);icon.pivot=new Vector2(0,1);icon.anchoredPosition=new Vector2(18,-18);icon.sizeDelta=new Vector2(72,72);Ensure<Image>(icon.gameObject);Txt(d,"Txt_Title","材料详情",28,new Vector2(108,-18),new Vector2(-126,-12));Txt(d,"Txt_Usage","",20,new Vector2(24,-104),new Vector2(-24,-150));Txt(d,"Txt_Source","",20,new Vector2(24,-208),new Vector2(-24,-250));Txt(d,"Txt_Flavor","",18,new Vector2(24,-280),new Vector2(-24,-24));PrefabUtility.SaveAsPrefabAsset(root,Path);}finally{PrefabUtility.UnloadPrefabContents(root);}AssetDatabase.SaveAssets();AssetDatabase.Refresh();Debug.Log("[WorkbenchMaterialsLayoutMigration] done");}
  static RectTransform R(Transform p,string n){Transform t=p.Find(n);if(t==null){GameObject g=new GameObject(n,typeof(RectTransform));g.transform.SetParent(p,false);t=g.transform;}return (RectTransform)t;} static T Ensure<T>(GameObject g)where T:Component{return g.GetComponent<T>()??g.AddComponent<T>();} static void Stretch(RectTransform r){r.anchorMin=Vector2.zero;r.anchorMax=Vector2.one;r.offsetMin=Vector2.zero;r.offsetMax=Vector2.zero;} static void Txt(Transform p,string n,string s,float z,Vector2 min,Vector2 max){RectTransform r=R(p,n);r.anchorMin=new Vector2(0,1);r.anchorMax=Vector2.one;r.pivot=new Vector2(.5f,1);r.offsetMin=min;r.offsetMax=max;TMP_Text t=Ensure<TextMeshProUGUI>(r.gameObject);t.text=s;t.font=TMP_Settings.defaultFontAsset;t.fontSize=z;t.alignment=TextAlignmentOptions.TopLeft;t.color=Color.white;t.raycastTarget=false;}
 }
}
#endif
